services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_API_PORT}:${BACKEND_API_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - api

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=arxivdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
