FROM python:3.12

# Install poetry
RUN pip install poetry

WORKDIR /app

# Copy poetry files and install dependencies
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-dev --no-interaction --no-ansi

# Copy application
COPY assets ./
COPY frontend.py .

CMD ["python", "frontend.py"]
